<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'Michael\\PiGhp\\' => array($typo3InstallDir . 'typo3conf/ext/pi_ghp/Classes'),
    'Pi\\OwnBlog\\' => array($typo3InstallDir . 'typo3conf/ext/own_blog/Classes'),
);
