<?php
return array (
  'autogenerated-2-c81e728d9d' => 
  array (
    'base' => 'http://dev-ghp-10.whocando.eu/autogenerated-2',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 2,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-3-eccbc87e4b' => 
  array (
    'base' => 'http://dev-ghp-10.whocando.eu/autogenerated-3',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 3,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-5-e4da3b7fbb' => 
  array (
    'base' => 'http://dev-ghp-10.whocando.eu/autogenerated-5',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 5,
    'routes' => 
    array (
    ),
  ),
  'guitarheartsproject' => 
  array (
    'base' => '/',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'Deutsch',
        'enabled' => true,
        'base' => '/',
        'typo3Language' => 'de',
        'locale' => 'de_DE',
        'iso-639-1' => 'ab',
        'websiteTitle' => '',
        'navigationTitle' => '',
        'hreflang' => '',
        'direction' => '',
        'flag' => 'global',
        'languageId' => 0,
      ),
    ),
    'rootPageId' => 1,
    'websiteTitle' => 'Guitar Hearts Project',
  ),
);
#