on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'u95803079-github'
          server: ${{ secrets.SERVER_IP }} 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './ghp/*'
          remote_path: '/kunden/homepages/16/d764565842/htdocs/guitarheartsproject/ghp'
          args: '-o ConnectTimeout=5'
